name: hps_direct

description: "SmartBank: A secure, modern Flutter banking app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  local_auth: ^2.1.6
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.12
  google_fonts: ^6.1.0
  intl_phone_field: ^3.1.0
  flutter_svg: ^2.0.7
  animations: ^2.0.0
  flutter_slidable: ^3.0.0
  intl: ^0.18.1
  table_calendar: ^3.0.8
  lucide_icons: ^0.257.0
  font_awesome_flutter: ^10.5.0
  flutter_staggered_grid_view: ^0.6.2
  go_router: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/FaceID.png
    - assets/visa_logo.png
    - assets/mastercard_logo.png
    - assets/apple_pay_logo.png
    - assets/barcode_sample.png
    - assets/rectangle.png
    - assets/ai1.png
    - assets/ai2.png
    - assets/ai3.png
    - assets/shadow3.png
    - assets/send.png
    - assets/user_chat.png
    - assets/ai_chat.png
    - assets/user_pic.jpg
    - assets/Banner.png
    - assets/cards_preview.jpg
    - assets/cards.jpg
    - assets/lock.png
    - assets/add_card.png
    - assets/reset1.jpg
    - assets/policy.jpg
    - assets/profile.png
    - assets/Logo_hps.png
    - assets/me_user.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Logo_hps.png"
