# ? Application Info
spring.application.name=user-service
server.port=9999

# ?? H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:userdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ? H2 Console (for Dev/Test)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ? JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ? JWT Security Properties
security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
security.jwt.expiration-time=3600000

# ? Debug Logging (Optional)
logging.level.org.springframework.security=TRACE


spring.cloud.consul.enabled=false
